# Maven --> these are comments
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: # the event that triggers the pipeline
- main # the branch that triggers the pipeline (meaning if code is pushed to this branch, the pipeline will run)

pool:
  name: 'testSelfHostedPool1' # Replace with the name of your agent pool

steps: # the various steps the pipeline will execute (in order)
- task: Maven@3 # maven task
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2 # copy files to azure staging directory task
  inputs:
    Contents: '**/.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1 # publish artifacts to azure task
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
